Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,8 +18,14 @@ jobs:
         run: |
           sudo apt-get update
           sudo apt-get install -y gradle
-      - name: Build with Gradle 
-        run: ./gradlew build
+      - name: Build with Gradle
+        run: |
+          gradle build
       - name: Run Tests with Gradle
-        run: ./gradlew test
-
+        run: |
+          gradle test
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/test/TEST-*.xml'
